version: '3.9'

services:
  database:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql-server-dev
    environment:
      MYSQL_DATABASE: 'taledb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - tale
  cache:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis-server-dev
    ports:
      - '6379:6379'
    networks:
      - tale

networks:
  tale:
    driver: bridge
    external: false
