spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/taledb
    username: user
    password: password

sql:
  r2dbc:
    enabled: true
    populators: [ './sql/schema.sql' ]
    cleaners: [ ]

server:
  port: 9000
