spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/citationdb?tlsVersion=TLSv1.2
    username: user
    password: password
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 9000
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: '*'

sql:
  r2dbc:
    enabled: true
    populators: [ './sql/schema.sql' ]
    cleaners: [ ]

validation:
  user:
    constraints:
      username-min: 5
      username-max: 32
      email-min: 8
      email-max: 64
      password-min: 6
      pasword-max: 64
    blacklist: blacklist.list