spring:
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?tlsVersion=TLSv1.2
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT:6379}

server:

  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info' ]

sql:
  r2dbc:
    enabled: false
    populators: [ ]
    cleaners: [ ]

validation:
  user:
    constraints:
      username-min: 5
      username-max: 32
      email-min: 8
      email-max: 64
      password-min: 6
      pasword-max: 64
